import { Bank } from './types';

export const SUPPORTED_BANKS: Bank[] = [
  {
    id: 'barclays',
    name: 'Barclays',
    fullName: 'Barclays Bank PLC',
    brandColor: '#00A4E4',
    textColor: '#ffffff',
    logoBg: 'bg-[#00a4e4]/10 hover:bg-[#00a4e4]/15 border-sky-100',
    hqLocation: 'London, UK',
    founded: 1690,
    openBankingStatus: 'Active',
  },
  {
    id: 'lloyds',
    name: 'Lloyds Bank',
    fullName: 'Lloyds Bank plc',
    brandColor: '#005B2E',
    textColor: '#ffffff',
    logoBg: 'bg-[#005b2e]/10 hover:bg-[#005b2e]/15 border-emerald-100',
    hqLocation: 'London, UK',
    founded: 1765,
    openBankingStatus: 'Active',
  },
  {
    id: 'nationwide',
    name: 'Nationwide',
    fullName: 'Nationwide Building Society',
    brandColor: '#002C6C',
    textColor: '#ffffff',
    logoBg: 'bg-[#002c6c]/10 hover:bg-[#002c6c]/15 border-indigo-100',
    hqLocation: 'Swindon, UK',
    founded: 1884,
    openBankingStatus: 'Active',
  },
  {
    id: 'natwest',
    name: 'NatWest',
    fullName: 'National Westminster Bank',
    brandColor: '#D6005C',
    textColor: '#ffffff',
    logoBg: 'bg-[#d6005c]/10 hover:bg-[#d6005c]/15 border-pink-100',
    hqLocation: 'London, UK',
    founded: 1968,
    openBankingStatus: 'Optimized',
  },
  {
    id: 'hsbc',
    name: 'HSBC',
    fullName: 'HSBC Holdings plc',
    brandColor: '#DB0011',
    textColor: '#ffffff',
    logoBg: 'bg-[#db0011]/10 hover:bg-[#db0011]/15 border-red-100',
    hqLocation: 'London, UK',
    founded: 1865,
    openBankingStatus: 'Active',
  },
  {
    id: 'santander',
    name: 'Santander UK',
    fullName: 'Santander UK plc',
    brandColor: '#EC0000',
    textColor: '#ffffff',
    logoBg: 'bg-[#ec0000]/10 hover:bg-[#ec0000]/15 border-rose-100',
    hqLocation: 'London, UK',
    founded: 2004,
    openBankingStatus: 'Active',
  },
];
